CREATE TABLE PERSON(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME varchar(50) NOT NULL,
  	AGE INT NOT NULL,
  	GENDER varchar(10) NOT NULL,
  	PRIMARY KEY (ID)
);
  
CREATE TABLE EMPLOYEE(
	ID BIGINT NOT NULL AUTO_INCREMENT,
  	NAME varchar(50) NOT NULL,
  	AGE INT NOT NULL,
  	GENDER varchar(10) NOT NULL,
  	SALARY DOUBLE NOT NULL,
  	EMPLOYER varchar(50) NOT NULL,
  	PRIMARY KEY (ID)
);